### PR TITLE
MAJOR UPDATE: 1:n category:sale

### PR DESCRIPTION
**Pull request by DanielPorter000866901**
cat_id now in sale table. Category is found with and updated with cat_id.
To change a sale's category, do so through update sale.
select statements return category name via a join

### CODE REVIEW

**Comment by DanielPorter000866901** [comment]
MAJOR DATABASE UPDATE!!

**Comment by DanielPorter000866901** [comment]
Some filter URLs have been removed, as they are now handled through the sales' URLs

**Comment by DanielPorter000866901** [comment]
/add-sale now expects a catId value.
/get-sale-filter no longer accepts an array, only a single value for catId
/update-sale now has an optional catId value for updating the category

**Comment by DanielPorter000866901** [comment]
/set-filters and /remove-filters are no longer available.

**Review by DanteNeverCries — APPROVED** [review]
autoapproved

**Comment by DanteNeverCries** [comment]
autoapproved

**Pull request merged**
